@CloudBnB.API_HostAddress = http://localhost:5252


### Landlords GetAll
GET {{CloudBnB.API_HostAddress}}/api/Landlords/GetAll/
Accept: application/json


### Locations GetAll
GET {{CloudBnB.API_HostAddress}}/api/Locations/GetAll
Accept: application/json
